---
- name: Setup VoltDB Dependencies
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Add APT key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EEA14886

    - name: Add Java APT repository
      apt_repository: 
        repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
        state: present

    - name: Install JDK 11
      apt: name='openjdk-11-jdk-headless' state=present

    - name: Install JRE 11
      apt: name='openjdk-11-jre-headless' state=present

    - name: Install Python 2.7
      apt: name='python2.7' state=present
    
    - name: Add /usr/bin/python link
      shell: 'ln -s /usr/bin/python2.7 /usr/bin/python' 
            
    - name: Install NTP
      apt: name='ntp' state=present
      
    - name: Disable THP
      shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled; echo never > /sys/kernel/mm/transparent_hugepage/defrag"
